= JSR 377 - Technical Compatibility Kit (TCK) 
:linkattrs:
:project-name: jsr377-tck
:plugin-version: 1.0.0-SNAPSHOT

Contains the TCK sources for link:https://jcp.org/en/jsr/detail?id=377[JSR-377].

image:http://img.shields.io/travis/jsr377/{project-name}/master.svg["Build Status", link="https://travis-ci.org/jsr377/{project-name}"]
image:http://img.shields.io/coveralls/jsr377/{project-name}/master.svg["Coverage Status", link="https://coveralls.io/r/jsr377/{project-name}"]
image:https://badges.gitter.im/Join%20Chat.svg[Gitter, link="https://gitter.im/jsr377/jsr377-api?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]

== Contributing

 - All contributions made by JSR377 Expert Group members are governed by the JSPA.
 - All contributions made by non Expert Group members are governed by the Apache Software License v2.

If you'd like to join the EG then please send your nomination to link:https://jcp.org/en/jsr/egnom?id=377[https://jcp.org/en/jsr/egnom?id=377, window="_blank"] Please bear in mind that you must be an JCP member and have signed the JSPA. You may require an additional signed Exhibit B depending on your membership type.

To get started (non-EG contributors), link:https://www.clahub.com/agreements/jsr377/jsr377-tck[sign the Contributor License Agreement, window="_blank"].

== Additional resources

 * link:http://jsr377.github.io/site/[JSR377 website, window="_blank"]
 * link:http://jsr377-api.40747.n7.nabble.com[Forum / Mailing List, window="_blank"]

== Building

This project uses link:http://gradle.org[Gradle] as build tool. The build is set as a composite build until final binary releases of JSR377 are posted.
Follow these instructions to build this project

[source]
----
$ git clone https://github.com/jsr377/jsr377-api.git jsr377/jsr377-api
$ git clone https://github.com/jsr377/jsr377-tck.git jsr377/jsr377-tck
$ cd jsr377/jsr377-converters
$ ./gradlew build
----
