name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout jsr377-api
        uses: actions/checkout@v2
        with:
          repository: jsr377/jsr377-api
          path: jsr377-api
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./main
      - name: Build with Gradle
        run: ./gradlew build -S
        working-directory: ./main
